# Site
name: "Bromenituk"
title: "Bromenituk"
description: "Kurzgeschichten, Langgeschichten, Kindergeschichten, komische Geschichten, Wortfetzen, Einkaufszettel, Briefe, Postkarten, Notizzettel und Hochzeitsreden."
tagline: "Einmal eine Portion Gedanken für alle"
subtitle: "Einmal eine Portion Gedanken für alle"
logo: 'assets/images/apple-touch-icon.png'
favicon: 'assets/images/apple-touch-icon.png'
baseurl: '/blog'
url: bromenituk.de
google_analytics: 'UA-86180764-1'
# disqus: 'Bromenituk'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
author: bromenituk

# Authors
authors:
  bromenituk:
    name: Bromenituk
    display_name: Bromenituk
    avatar: 'assets/images/avatar.png'
    # email: wowthemesnet@gmail.com
    web: https://bromenituk.de
    # twitter: https://twitter.com/wowthemesnet
    description: "Bromenituk ist: eine junge Kölnerin, Kinderbuchautorin, Kochbuchautorin, Texterin, Mami, Läuferin und Lebefrau."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page-:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# same sized covered images ("enabled" or "disabled")
coverimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
